# Generated by Django 3.1.12 on 2025-05-05 12:58

from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoaiMonAn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_loai', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('mo_ta', models.TextField(blank=True, null=True)),
                ('hinh_anh_dai_dien', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'loai_mon_an',
            },
        ),
        migrations.CreateModel(
            name='VungMien',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_vung', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('mo_ta', models.TextField(blank=True, null=True)),
                ('ban_do', djongo.models.fields.JSONField(blank=True, null=True)),
                ('hinh_anh_dai_dien', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'vung_mien',
            },
        ),
        migrations.CreateModel(
            name='MonAn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_mon_an', models.CharField(max_length=255)),
                ('ten_mon_an_en', models.CharField(blank=True, max_length=255, null=True)),
                ('mo_ta_ngan', models.TextField(blank=True, null=True)),
                ('nguyen_lieu', djongo.models.fields.JSONField()),
                ('cach_lam', djongo.models.fields.JSONField()),
                ('hinh_anh', models.CharField(blank=True, max_length=255, null=True)),
                ('tags', djongo.models.fields.JSONField(blank=True, null=True)),
                ('luot_xem', models.IntegerField(default=0)),
                ('ngay_tao', models.DateTimeField(auto_now_add=True)),
                ('ngay_cap_nhat', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(unique=True)),
                ('loai', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mon_ans', to='food_api.loaimonan')),
                ('vung_mien', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mon_ans', to='food_api.vungmien')),
            ],
            options={
                'db_table': 'mon_an',
            },
        ),
    ]
