# Generated by Django 4.1.13 on 2025-05-05 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loaimonan',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='monan',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='vungmien',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
